<?php

namespace App\Models;

use App\Mail\QnaCreated;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Mail;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class Qna extends Model implements HasMedia
{
    use HasFactory, InteractsWithMedia;

    protected $guarded = ["id"];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::created(function($model){
            // ceo@co-worker.co.kr
            Mail::to("kim1004pd@naver.com")->send(new QnaCreated($model));
        });
    }

    public function registerMediaCollections():void
    {
        $this->addMediaCollection('files');
    }

    public function getFilesAttribute()
    {
        $items = [];

        if($this->hasMedia('files')) {
            $medias = $this->getMedia('files');

            foreach($medias as $media){
                $items[] = [
                    "name" => $media->file_name,
                    "url" => $media->getFullUrl()
                ];
            }
        }

        return $items;
    }
}
